### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [radum/dotfiles#10]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README.md`](https://github.com/radum/dotfiles/blob/1cdbdefc925a10bd2628b8875d72b8945c8613a5/.deprecated/README.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by radum** [comment]
Thanks @reitermarkus, the link was part of my deprecated folder but I have updated the file either way.
